# action.yml
name: 'Planemo'
description: 'Greet someone and record the time'
inputs:
  planemo-arguments:  # id of input
    description: 'planemo command line parameters'
    required: true
    default: 'lint'
outputs:
  test-result: # id of output
    description: 'Test results'
runs:
  using: 'docker'
  image: 'docker://mvdbeek/planemo-actions:19.09-0'
  args:
    - ${{ inputs.planemo-arguments }}
