name: Publish planemo-action
on: [push]

jobs:
  build:
    name: Publish planemo-action image to docker registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: docker build -t mvdbeek/planemo-action:latest --build-arg galaxy_branch=release_19.09 .
      - name: publish to docker registry
        uses: manusa/actions-publish-docker@master
        with:
          name: mvdbeek/planemo-action:latest
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
